---
image: docker:18

stages:
  - deploy
  - test

deploy-app-to-container:
  stage: deploy
  environment: production 
  image: docker
  services:
    - docker:dind
  before_script:
    - echo "Log into docker container registry in GitLab"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script: 
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  after_script:
    - docker logout


test-the-container:
  stage: test
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER"  "$CI_REGISTRY" --password-stdin
  script:
    - docker pull $REPO_URL:$CI_COMMIT_SHA
    - docker run -t $REPO_URL:$CI_COMMIT_SHA .
    - docker push $REPO_URL:$CI_COMMIT_SHA
  after_script:
    - docker logout 
